# Generated by Django 3.1.2 on 2020-10-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilestatus',
            options={'verbose_name_plural': 'Profile Statuses'},
        ),
    ]
